# Python_Basic_Program_Assignment_8

In [ ]:
1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
a=[[1,2,3],
  [4,5,6],
  [7,8,9]]
b=[[9,8,7],
  [6,5,4],
  [3,2,1]]
c=np.array(a)+np.array(b)
c

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
2. Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np
a=[[1,2,3],
  [4,5,6],
  [7,8,9]]
b=[[9,8,7],
  [6,5,4],
  [3,2,1]]
c=np.array(a).dot(np.array(b))
c

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
3. Write a Python Program to Transpose a Matrix?

In [5]:
import numpy as np
a=[[1,2,3],
  [4,5,6],
  [7,8,9]]
b=np.array(a).transpose()
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
4. Write a Python Program to Sort Words in Alphabetic Order?


In [15]:
x=input("Enter string:")
word=x.lower().split()
word.sort()
for i in word:
    print(i)



Enter string:My name is Neha
is
my
name
neha


In [ ]:
5. Write a Python Program to Remove Punctuation From a String?

In [16]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
a="Hey!! everone, I am Neha Anubhuti; I offer you a discout of [50%]"
no_pun=""
for i in a:
    if i not in punctuations:
        no_pun=no_pun+i
no_pun        
        

'Hey everone I am Neha Anubhuti I offer you a discout of 50'